#################################################
# 执行前请阅读说明 | Read before running
# 详细介绍参考: README.md

# download.sh
# 提前下载二进制文件减少每个主机的下载开销
# 可修改download.sh自定义组件版本
# 会自动生成新的证书, mac需要提前安装一些软件

# 关于自定义ca证书
# 证书名强制不能更改, 必须和默认证书名称一致
# 保证自定义的证书能被cfssl识别

# 变量
# 必要配置实现变量控制, 参考: defaults/main.yaml
# 为了保证必要配置统一, 尽量必要尝试主机级别的变量配置
# 如需自定义某个变量, 请设置playpook/host_all级别

# 配置
# 避免臃肿配置, 更多参数和配置需自行修改, 当前基本够用
# 参数变动请修改 templates/ files/ 下的文件内容
#################################################

#################################################
# 主机初始化 | Node bootstrap
# 包含架构工具、Swap/内核参数等基础配置
#################################################
- name: Bootstrap nodes
  hosts: init-node
  roles:
    - init-node
#################################################
# etcd 部署 | Deploy etcd cluster
# 推荐使用与 master 对齐的堆叠模式
#################################################
- name: Deploy etcd
  hosts: etcd
  roles:
    - etcd
#################################################
# 安装 Kubernetes 控制面 | Deploy control-plane
#################################################
- name: Deploy kube-master
  hosts: kube-master
  roles:
    - kube-master
#################################################
# 安装 Kubernetes 节点组件 | Deploy worker components
# 未配置外部 LB 时默认启用静态 nginx 代理 apiserver
#################################################
- name: Deploy kube-node
  hosts: kube-node
  roles:
    - kube-node
#################################################
# Kubernetes 附加组件安装 | Deploy addons
# 如需自定义可按需注释此阶段
#################################################
- name: Deploy cluster addons
  hosts: kube-master[0]
  roles:
    - kube-components
