apiVersion: v1
kind: Pod
metadata:
  name: kube-api
  namespace: kube-system
  labels:
    k8s-app: kube-nginx
spec:
  hostNetwork: true
  nodeSelector:
    beta.kubernetes.io/os: linux
  priorityClassName: system-node-critical
  containers:
  - name: api-proxy
    image: nginx:1.24.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /etc/nginx
      name: etc-nginx
      readOnly: true
  volumes:
  - name: etc-nginx
    hostPath:
      path: /etc/kubernetes/nginx
