- name: Create ssl certs directory
  ansible.builtin.file:
    path: "{{ kube_cert_dir }}"
    state: directory
    mode: '0755'

- name: Copy ssl CA to host
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/packages/ssl/{{ item }}"
    dest: "{{ kube_cert_dir }}/{{ item }}"
    mode: '0644'
  loop:
    - "ca-config.json"
    - "k8s-ca.pem"
    - "k8s-ca-key.pem"

- name: Script to generate kubelet ssl certs
  ansible.builtin.script: "gen_kubelet_ssl.sh"
  environment:
    kube_cert_dir: "{{ kube_cert_dir }}"
    kube_master_endpoint: "{{ kube_master_endpoint }}"
    kube_node_ip: "{{ kube_node_ip }}"
    kube_node_name: "{{ kube_node_name }}"

- name: Script to generate kube-proxy ssl certs
  ansible.builtin.script: "gen_kube_proxy_ssl.sh"
  environment:
    kube_cert_dir: "{{ kube_cert_dir }}"
    kube_master_endpoint: "{{ kube_master_endpoint }}"
