- name: Check clean kube-master
  ansible.builtin.include_tasks: "clean_kube_node.yaml"
  when: kube_node_clean

- name: Gen kube-master host vars
  ansible.builtin.set_fact:
    kube_master_ip: "{{ internal_ip | default(ansible_host) }}"

- name: Check kube-node no install
  ansible.builtin.meta: end_host
  when: kube_master_no_install | default(false) | bool

- name: Copy binary files to host
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/packages/kube/{{ ansible_architecture }}/{{ item }}"
    dest: "{{ bin_dir }}/{{ item }}"
    mode: '0755'
    owner: root
    group: root
  loop:
    - "kube-apiserver"
    - "kube-controller-manager"
    - "kube-scheduler"
    - "kubectl"

- name: Script to generate ssl certs
  ansible.builtin.include_tasks: "gen_ssl.yaml"

- name: Enable apiserver audit log
  ansible.builtin.include_tasks: "kube_audit.yaml"
  when: enable_apiserver_audit | default(false) | bool

- name: Copy systemd file to host
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: '0644'
  loop:
    - "kube-apiserver.service"
    - "kube-controller-manager.service"
    - "kube-scheduler.service"

- name: Systemctl daemon_reload
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    daemon_reload: true
  failed_when: false
  loop:
    - "kube-apiserver"
    - "kube-controller-manager"
    - "kube-scheduler"

- name: Ensure etcd is running and enabled
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - "kube-apiserver"
    - "kube-controller-manager"
    - "kube-scheduler"

- name: Check kube health
  ansible.builtin.command: "{{ bin_dir }}/kubectl get componentstatuses"
  register: kube_health
  retries: 5
  delay: 5
  until: kube_health.rc == 0
  changed_when: false

- name: Print kube health
  ansible.builtin.debug:
    msg: "{{ kube_health.stdout_lines }}"

- name: Enable bootstrap token auth
  ansible.builtin.include_tasks: "kube_rbac.yaml"
  run_once: true
