kube_apiserver_port: 6443
containerd_data_dir: "/var/lib/containerd"
kubelet_data_dir: "/var/lib/kubelet"
services_cidr: "10.254.0.0/16"
cluster_ip: "{{ services_cidr | ipmath(1) }}"
cluster_dns: "{{ services_cidr | ipmath(10) }}"
pod_cidr: "10.234.0.0/16"
kube_cert_dir: "/etc/kubernetes/pki"
cluster_domain: "cluster.local"
kube_proxy_mode: "ipvs"
resolv_conf: "/etc/resolv.conf"

# 是否用IP定义hostname-override参数
# 默认用 {{ inventory_hostname }}
use_ip_as_hostname: false
kube_node_role: node
# cilium替代kube-proxy
cilium_replace_kube_proxy: false
# 是否需要通过ansible手动倒入镜像
# 需要提前在download脚本中配置相关镜像的下载
offline_pull_images: false

# 不执行安装
kube_node_no_install: false
# 是否清理数据, 不会清理证书文件, 防止影响到kube-master的正常使用
kube_node_clean: false
# 二进制文件目录
bin_dir: "/usr/bin"
