# RBAC 配置 | Bootstrap RBAC resources
- name: RBAC | Copy bootstrap manifests to node | 下发 RBAC 清单
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: '0755'
  loop:
    - "kube-apiserver-to-kubelet.yaml"
    - "kubelet-bootstrap.yaml"

- name: RBAC | Apply apiserver-to-kubelet permissions | 应用 apiserver 到 kubelet 权限
  ansible.builtin.shell: "kubectl apply -f /tmp/kube-apiserver-to-kubelet.yaml"
  register: kube_apiserver_to_kubelet
  failed_when: false

- name: RBAC | Show apiserver-to-kubelet apply result | 输出 apiserver RBAC 结果
  ansible.builtin.debug:
    msg: "kube-apiserver to kubelet RBAC creation result: {{ kube_apiserver_to_kubelet.stdout }}"

- name: RBAC | Apply kubelet bootstrap permissions | 应用 kubelet bootstrap 权限
  ansible.builtin.shell: "kubectl apply -f /tmp/kubelet-bootstrap.yaml"
  register: kubelet_bootstrap
  failed_when: false
  when: enable_bootstrap_token_auth

- name: RBAC | Show kubelet bootstrap apply result | 输出 bootstrap RBAC 结果
  ansible.builtin.debug:
    msg: "kubelet bootstrap RBAC creation result: {{ kubelet_bootstrap.stdout }}"
  when: enable_bootstrap_token_auth
